site_name: Catln
repo_name: zachgk/catln
repo_url: https://github.com/zachgk/catln/

theme:
  name: material
  custom_dir: docOverrides

markdown_extensions:
  - codehilite
  - toc:
      permalink: true

google_analytics:
  - G-PMHTDK53PT
  - auto

plugins:
  - search

docs_dir: 'docs'

nav:
  - 'README.md'
  - Design:
      - 'philosophy/README.md'
      - 'philosophy/basics.md'
      - 'philosophy/typeTheory.md'
      - Metaprogramming:
        - 'philosophy/metaprogramming.md'
        - 'philosophy/choice.md'
        - 'philosophy/macros.md'
        - 'philosophy/languageCompilation.md'
        - 'philosophy/compilerErrorStatement.md'
      - Testing:
        - 'philosophy/testing.md'
        - 'philosophy/arrowTesting.md'
        - 'philosophy/assertions.md'
      - 'philosophy/context.md'
      - 'philosophy/optimization.md'
      - 'philosophy/syntacticSugar.md'
      - Documentation:
        - 'philosophy/documentation.md'
        - 'philosophy/naming.md'
      - 'philosophy/modules.md'
      - 'philosophy/debugging.md'
  - 'syntax.md'
  - 'building.md'
  - Contributor
    - 'contrib/building.md'
    - 'contrib/organization.md'
